name: Docker_login

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  first:
    runs-on: ubuntu-latest
    steps:
        - name: Login_to_Docker_Hub
          uses: actions/checkout@v2
          with:
            DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
            DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

