name: readme

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  first:
    runs-on: ubuntu-latest
    steps: 
      - name: write in read me
        run: echo "write hello heba in read me file" > README.md
      - name: printing 
        run: cat README.md
