name: readme

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  first:
    runs-on: ubuntu-latest
    steps: 
      - name: printing
        run: cat /he15ba11/Solar-System-/README.md
